# Generated by Django 5.0 on 2023-12-19 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_course_owner'),
        ('lessons', '0002_lesson_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_payment', models.DateTimeField(auto_now_add=True, verbose_name='Дата оплаты')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за покупку')),
                ('payment_method', models.CharField(choices=[('наличные', 'наличные'), ('перевод', 'перевод')], max_length=25, verbose_name='способ оплаты')),
                ('course_pay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course', to='courses.course', verbose_name='оплаченный  Курс')),
                ('lesson_pay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson', to='lessons.lesson', verbose_name='оплаченный  Урок')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
    ]
